Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Breadlesscode.SimpleEditorExtend:UiPlugin':
            resource: resource://Breadlesscode.SimpleEditorExtend/Public/UiPlugin/Plugin.js
        stylesheets:
          'Breadlesscode.SimpleEditorExtend:UiPlugin':
            resource: resource://Breadlesscode.SimpleEditorExtend/Public/UiPlugin/Plugin.css
